version: "3"

services:
  web:
    container_name: week3-web-snapshot-web
    build: .
    ports:
      - "50034:80"

  db:
    container_name:  week3-web-snapshot-db
    hostname: db
    image: redis:4.0.14-alpine
    environment:
      - FLAG=0xGame{aef421d4-0f35-4b82-b7ee-0dbea46b6333}